name: Check Reward Pool

on:
  schedule:
    # Run once every hour at minute 0
    - cron: '0 * * * *'
    # Also run once every day at a different time (4:30 UTC) to ensure coverage
    - cron: '30 4 * * *' 
  workflow_dispatch: # Allow manual triggering
  push:
    paths:
      - '.github/workflows/check-reward.yml' # Run when this workflow file is updated

jobs:
  check-reward:
    runs-on: ubuntu-latest
    timeout-minutes: 5 # Set a timeout to prevent hung jobs
    
    steps:
      - name: Check time
        run: echo "Current time is $(date)"
      
      - name: Trigger Check Reward API with retry logic
        run: |
          # Retry up to 3 times with 10 second delays
          for i in {1..3}; do
            echo "Attempt $i to call the API..."
            RESPONSE=$(curl -s -m 30 -X POST "https://hashkey-hodlium-ten.vercel.app/api/check-reward")
            API_STATUS=$?
            
            if [ $API_STATUS -eq 0 ]; then
              echo "API Response: $RESPONSE"
              
              # Check if the API returned a success response
              if echo "$RESPONSE" | grep -q '"success":true'; then
                echo "Reward pool updated successfully!"
                exit 0
              elif echo "$RESPONSE" | grep -q '"message":"No update needed"'; then
                echo "No update needed at this time."
                exit 0
              else
                echo "API returned an unexpected response. Will retry if attempts remain."
              fi
            else
              echo "API call failed with status $API_STATUS. Will retry if attempts remain."
            fi
            
            if [ $i -lt 3 ]; then
              echo "Waiting 10 seconds before retry..."
              sleep 10
            fi
          done
          
          echo "All retry attempts failed. Please check your API endpoint."
          exit 1
          
      - name: Verify API is accessible (on failure)
        if: ${{ failure() }}
        run: |
          echo "Checking if the API endpoint is accessible..."
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -m 10 "https://hashkey-hodlium-ten.vercel.app/api/check-reward")
          CURL_STATUS=$?
          
          if [ $CURL_STATUS -eq 0 ]; then
            echo "API is accessible with HTTP Status: $HTTP_STATUS"
            if [ "$HTTP_STATUS" -eq 200 ]; then
              echo "API is returning a 200 status but the reward check failed for another reason."
            else
              echo "API is returning a non-200 status: $HTTP_STATUS"
            fi
          else
            echo "Could not connect to API. Curl exit status: $CURL_STATUS"
          fi